import {
  type DeliveryMode,
  type DeliveryProblem,
  type MessageProblem,
  type SendFailure,
  type TestFailure,
} from "@/domain/campaign"
import { type CampaignStatusFilter } from "@/domain/lists"

const people = (n: string | number) => `${n} ${n === 1 || n === "1" ? "person" : "people"}`

export const CAMPAIGNS = {
  title: "Campaigns",
  subtitle: "One-off pushes to an audience you choose, in every app language.",
  new: "New campaign",
  statuses: {
    all: "All",
    draft: "Drafts",
    scheduled: "Scheduled",
    sending: "Sending",
    sent: "Sent",
    canceled: "Canceled",
    failed: "Failed",
  } satisfies Record<CampaignStatusFilter, string>,
  columns: {
    campaign: "Campaign",
    status: "Status",
    audience: "Audience",
    recipients: "Recipients",
    when: "Sent / scheduled",
  },
  emptyTitle: "No campaigns",
  emptyAll: "Write a push, choose who gets it, test it on your phone, then send it now or later.",
  emptyFiltered: "No campaign has this status.",
  noMessage: "No message yet",
  edited: (when: string) => `Edited ${when}`,
  people,

  editor: {
    back: "Campaigns",
    newTitle: "New campaign",
    subtitle: "A draft: test it on your phone, then send it now or schedule it.",
    notFound: "This campaign doesn't exist (or was deleted).",
    save: "Save draft",
    saved: "Draft saved",
    created: "Draft created",
    discard: "Discard changes",
    send: "Send…",
    unsaved: "Unsaved changes — sending or testing saves them first.",
    counter: (length: number, max: number) => `${length}/${max}`,
    fixErrors: "Some fields need attention.",

    message: {
      title: "Message",
      hint: "Write it in English or Turkish, then translate it into the other app languages.",
      name: "Internal name",
      nameHint: "Only admins see it.",
      namePlaceholder: "October comeback",
      source: "Written in",
      pushTitle: "Title",
      pushBody: "Message",
      titlePlaceholder: "Your streak is waiting 🔥",
      bodyPlaceholder: "Five minutes today keeps it alive. Pick up where you left off.",
      translate: "Translate to all languages",
      translating: "Translating…",
      translated: "Translated into every app language",
      translateNeedsText: "Write the title and the message first (within the limits).",
      overwriteTitle: "Replace the translations?",
      overwriteBody: (n: number) =>
        `${n} ${n === 1 ? "language has" : "languages have"} text that isn't the last machine translation. Translating replaces it.`,
      overwriteConfirm: "Translate",
      sourceChanged:
        "The source changed after the last translation: translate again to update the other languages.",
    },

    translations: {
      title: "Translations",
      hint: "Every app language. Users whose language is missing get English, else the source language.",
      ready: (ready: number, total: number) => `${ready} of ${total} ready`,
      missing: (n: number) => `${n} missing`,
      source: "Source",
      edited: "Edited",
      problems: {
        missing: "Missing",
        incomplete: "Needs both",
        title_long: "Title too long",
        body_long: "Message too long",
      } satisfies Record<MessageProblem, string>,
      fallback: (language: string) => `Gets the ${language} text`,
      reset: "Back to the machine translation",
      onlyMissing: "Needs work",
      allShown: "All",
      allReady: "Every language is ready.",
    },

    audience: {
      title: "Audience",
      hint: "Who gets it. Filters combine: a user must match every one.",
      segment: "Who",
      levels: "Levels",
      levelsHint: "None checked: every level.",
      languages: "App languages",
      languagesAll: "Every language",
      languagesAdd: "Choose languages",
      languagesSearch: "Search languages…",
      inactive: "Not seen for at least",
      active: "Seen within the last",
      days: "days",
      daysHint: "Empty: no filter.",
      podcasts: "Following",
      podcastsHint: "Followers of any of these podcasts. None: no filter.",
      addPodcast: "Add a podcast",
      removePodcast: "Remove",
      contradiction: "Nobody can match: “seen within” must be longer than “not seen for”.",
    },

    reach: {
      title: "Reach",
      matched: "Match the audience",
      reachable: "Will get it",
      reachableHint: "Push on and news allowed",
      languages: "Top languages",
      more: (n: number) => `+${n} more`,
      nobody: "Nobody in this audience can get a push right now.",
      failed: "Couldn't count the audience.",
    },

    link: {
      title: "When tapped",
      hint: "What the app opens.",
      type: "Opens",
      episode: "Episode",
      chooseEpisode: "Choose an episode",
      changeEpisode: "Change",
      pickerTitle: "Choose the episode",
      unknownEpisode: "This episode isn't among the latest ones — it may have been deleted.",
      level: "Level",
      userLevel: "The user's own level",
      podcast: "Podcast",
      choosePodcast: "Choose a podcast",
      noAudio: "No audio at this level",
    },

    image: {
      title: "Image",
      hint: "Optional. Shown when the push is expanded (and as a thumbnail on iOS).",
      useCover: "Use the episode's cover",
    },

    delivery: {
      title: "Delivery",
      hint: "When it goes out — chosen when you send, not saved with the draft.",
      modes: {
        now: "Now",
        at: "At a set time",
        local: "At each user's local time",
      } satisfies Record<DeliveryMode, string>,
      modeHints: {
        now: "Starts within a minute.",
        at: "The same moment for everyone.",
        local: "Goes out as each time zone reaches the date and time.",
      } satisfies Record<DeliveryMode, string>,
      at: "Send at",
      atHint: (zone: string) => `Your time (${zone}).`,
      date: "Date",
      time: "Time",
      problems: {
        at_missing: "Pick a date and a time.",
        at_past: "Pick a time in the future.",
        date_missing: "Pick a date.",
        date_past: "Pick today or a later date.",
        time_missing: "Pick a time.",
      } satisfies Record<DeliveryProblem, string>,
      lateToday: "Today: users whose time already passed more than an hour ago are skipped.",
      quiet: "Respect quiet hours",
      quietHint: (from: string, to: string) =>
        `Users in quiet hours (${from}–${to} their time) get it at ${to}.`,
      quietOff: "Everyone gets it at the chosen time, even at night.",
      localInQuiet: (time: string, to: string) =>
        `${time} is inside the quiet hours: with them respected, users get it at ${to}.`,
    },

    preview: {
      title: "Preview",
      hint: "On an iPhone lock screen.",
      language: "Language",
      empty: "Write a title and a message to see the push.",
      fallback: (wanted: string, used: string) => `No ${wanted} text: these users get the ${used} one.`,
      now: "now",
      clock: "9:41",
      expanded: "Expanded",
      missingSuffix: "no text",
    },

    checklist: {
      title: "Before sending",
      name: "A name",
      source: (language: string) => `A ${language} message`,
      translations: (ready: number, total: number) => `${ready} of ${total} languages`,
      link: "Where a tap goes",
      reach: (n: string) => `${n} reachable`,
      reachUnknown: "Reach being counted",
    },

    test: {
      button: "Send test",
      title: "Send a test push",
      hint: "Right away, to one person, ignoring limits and quiet hours. Unsaved changes are saved first.",
      toMe: "Me",
      toMeHint: (email: string) =>
        `${email} — signed in to the GlotCast app on a phone with notifications allowed.`,
      toOther: "Someone else",
      otherPlaceholder: "User ID or email",
      otherInvalid: "Enter a user ID or an email address.",
      language: "Language",
      theirLanguage: "Their app language",
      send: "Send test",
      sent: "Test push sent — check the phone.",
      sentNoId: "Test push handed over (OneSignal gave no id).",
      failures: {
        no_account:
          "No app account with this identity: sign in to the GlotCast app with the same account (same email) first.",
        no_subscription:
          "That account has no push subscription: open the app on a phone, allow notifications, then try again.",
        not_configured: "OneSignal isn't configured on the API (ONESIGNAL_APP_ID / ONESIGNAL_API_KEY).",
        onesignal_down: "OneSignal didn't answer. Try again in a moment.",
        onesignal_refused: "OneSignal refused the push.",
        no_message: "The campaign has no message yet: write one and save.",
        other: "The test push couldn't be sent.",
      } satisfies Record<TestFailure, string>,
    },

    sendDialog: {
      title: "Send this campaign?",
      reach: (n: string) => `It goes to ${n} ${n === "1" ? "person" : "people"} (push on, news allowed).`,
      reachLoading: "Counting the audience…",
      nobody: "Nobody in this audience can get it right now — it will be sent to no one.",
      when: "When",
      audience: "Audience",
      quietOn: (to: string) => `Quiet hours respected: users in them get it at ${to}.`,
      quietOff: "Quiet hours ignored.",
      sendNow: "Send now",
      schedule: "Schedule",
      sent: "Campaign is going out",
      scheduled: "Campaign scheduled",
      noDelivery: "Choose when it goes out (Delivery).",
      failures: {
        not_configured:
          "OneSignal isn't configured on the API: set ONESIGNAL_APP_ID and ONESIGNAL_API_KEY in its environment.",
        disabled:
          "Notifications are switched off on the API: set NOTIFICATIONS_ENABLED=true in its environment.",
        no_source_message: "Write the message in the source language first.",
        past: "That time has passed — pick a later one.",
        not_draft: "This campaign isn't a draft anymore. Reload the page.",
        other: "The campaign couldn't be sent.",
      } satisfies Record<SendFailure, string>,
    },
  },

  detail: {
    back: "Campaigns",
    lines: {
      scheduled: (when: string) => `Scheduled · ${when}`,
      sending: "Going out now",
      sent: (when: string) => `Sent ${when}`,
      canceled: "Canceled",
      failed: "Nothing could be sent",
    },
    autoRefresh: "Updates by itself while it goes out.",
    cancel: "Cancel sending",
    cancelTitle: "Stop this campaign?",
    cancelBody: "Pushes that haven't gone out yet are canceled; those already sent stay sent.",
    cancelConfirm: "Stop it",
    canceled: "Campaign canceled",
    duplicate: "Duplicate as draft",
    duplicated: "Copied into a new draft",
    copyName: (name: string) => `${name} (copy)`.slice(0, 120),
    delete: "Delete",
    deleteTitle: "Delete this campaign?",
    deleteBody: (name: string) => `“${name}” and its send log are removed for good, with its numbers.`,
    deleted: "Campaign deleted",
    deleteLive: "Cancel it first: a scheduled or sending campaign can't be deleted.",

    stats: {
      title: "Results",
      hint: "Our counts, plus OneSignal's (cached 5 minutes).",
      refreshed: (when: string) => `OneSignal checked ${when}`,
      refresh: "Refresh from OneSignal",
      recipients: "Recipients",
      recipientsHint: "Matched and reachable when it went out",
      sent: "Sent",
      sentHint: (queued: string) => `${queued} still queued`,
      sentDone: "Handed to OneSignal",
      delivered: "Delivered",
      deliveredBy: {
        received: "Confirmed by devices (OneSignal)",
        successful: "Accepted by Apple / Google (OneSignal)",
        sent: "OneSignal hasn't reported yet",
      },
      clicked: "Clicked",
      clickedBy: {
        converted: (opened: string) => `OneSignal clicks · ${opened} opens seen by the app`,
        opened: "Opens the app reported",
      },
      ctr: "Click rate",
      ctrHint: "Clicked ÷ delivered",
      failed: "Failed",
      failedHint: "Refused or expired",
      unreachable: "Unreachable",
      unreachableHint: "No push subscription",
      skipped: "Skipped",
      skippedHint: "Canceled, or their time had passed",
    },

    languages: {
      title: "By language",
      hint: "Who got which language (fallbacks included).",
      columns: { language: "Language", recipients: "Recipients", opened: "Opened", rate: "Open rate" },
      empty: "Nothing has gone out yet.",
    },

    messages: {
      title: "Messages",
      hint: "As written. A missing language falls back to English, then the source.",
      source: "Source",
    },

    facts: {
      title: "Details",
      audience: "Audience",
      link: "Opens",
      delivery: "Delivery",
      quietHours: "Quiet hours",
      quietOn: "Respected",
      quietOff: "Ignored",
      image: "Image",
      noImage: "None",
      createdBy: "Created by",
      created: "Created",
      sentAt: "Sent",
      id: "ID",
      sendLog: "Open in the send log",
    },
  },

  errors: {
    name: "Give the campaign a name (only admins see it).",
    nameLong: "At most 120 characters.",
    titleMissing: "A title is needed.",
    titleLong: "At most 60 characters.",
    bodyMissing: "A message is needed.",
    bodyLong: "At most 180 characters.",
    days: "A whole number of days from 1 to 3650.",
    episode: "Choose the episode.",
    podcast: "Choose the podcast.",
    url: "Enter a full URL (https://…).",
    podcasts: "At most 100 podcasts.",
  },
}
