export const HOME = {
  title: "Home screen",
  subtitle: "What the app shows first: the slider, the home lists and the discover lists. Drag to reorder.",
  slider: "Slider",
  sliderHint: "Episodes in the home slider, in order. They need a banner (landscape image).",
  homeLists: "Home lists",
  homeListsHint: "Lists on the home screen, in order (ten episodes each).",
  exploreLists: "Discover lists",
  exploreListsHint: "Lists on the discover screen, in order.",
  addEpisode: "Add episodes",
  addList: "Add a list",
  noListsLeft: "Every list is already here.",
  noLists: "No lists yet — create them on the Lists page.",
  empty: "Nothing here yet.",
  noBanner: "No banner",
  unknownEpisode: "Unknown episode",
  unknownList: "Unknown list",
  save: "Save home screen",
  saved: "Home screen saved",
  unsaved: "Unsaved changes on the home screen.",
  discard: "Discard",
  max: (n: number) => `Up to ${n}.`,
  episodesCount: (n: number) => `${n} ${n === 1 ? "episode" : "episodes"}`,
}
