export const NAV_COPY = {
  groups: {
    overview: "Overview",
    content: "Content",
    curation: "Curation",
    engagement: "Engagement",
    people: "People",
  },
  dashboard: "Dashboard",
  podcasts: "Podcasts",
  episodes: "Episodes",
  categories: "Categories",
  lists: "Lists",
  home: "Home screen",
  campaigns: "Campaigns",
  automations: "Automations",
  sendLog: "Send log",
  users: "Users",
  audit: "Audit log",
  search: "Search",
  searchHint: "Jump to a page, a podcast or an episode",
  searchPlaceholder: "Type a page, a podcast or an episode…",
  pages: "Pages",
  foundPodcasts: "Podcasts",
  foundEpisodes: "Episodes",
  actions: "Create",
  newPodcast: "New podcast",
  newEpisode: "New episode",
  newCampaign: "New campaign",
  noResults: "Nothing found.",
  searching: "Searching…",
  notFoundTitle: "Page not found",
  notFoundBody: "There's nothing at this address.",
  backHome: "Back to the dashboard",
}
