export const SEND_LOG = {
  title: "Send log",
  subtitle:
    "Every push GlotCast planned — sent, skipped (and why) or tested — newest first. Kept 90 days (skips 14).",
  allKinds: "All kinds",
  allStatuses: "All statuses",
  allCampaigns: "All campaigns",
  kind: "Kind",
  status: "Status",
  campaign: "Campaign",
  userPlaceholder: "Filter by user ID",
  userInvalid: "Paste a whole user ID (from the user's page).",
  columns: {
    when: "When",
    user: "User",
    kind: "Kind",
    status: "Status",
    language: "Language",
    message: "Message",
    opened: "Opened",
  },
  due: (when: string) => `Due ${when}`,
  notSent: "No text: it wasn't sent.",
  notOpened: "—",
  filterUser: "Only this user",
  filterCampaign: "Only this campaign",
  emptyTitle: "Nothing in the log",
  emptyFiltered: "No push matches these filters.",
  emptyAll: "Nothing has been planned yet. Automations start off — switch them on under Automations.",
}
