import { type CoverAspect, type CoverModel, type CoverStyle } from "@/schemas/admin"

export const COVERS = {
  title: "Cover generator",
  hint: "Write a prompt from the transcript in one of five styles, then draw it with Gemini or OpenAI.",
  podcastHint: "Write a prompt from the description, or type your own, then draw it with Gemini or OpenAI.",
  source: "Write from",
  sourceLevel: (level: string) => `${level} transcript`,
  noSource: "No transcript yet: type a prompt yourself, or transcribe a level first.",
  noDescription: "Add a description to write a prompt from it, or type your own.",
  style: "Style",
  styles: {
    "vibrant-gradient": "Vibrant gradient",
    "cinematic-photo": "Cinematic photo",
    "minimal-editorial": "Minimal editorial",
    risograph: "Risograph print",
    "bold-pop": "Bold pop",
  } satisfies Record<CoverStyle, string>,
  styleHints: {
    "vibrant-gradient": "Colourful gradients, glow, stylized poster",
    "cinematic-photo": "Photoreal, film grain, a movie still",
    "minimal-editorial": "Negative space, two or three colours",
    risograph: "Halftone, off-register vintage ink",
    "bold-pop": "Flat, high-contrast, Bauhaus / Saul Bass",
  } satisfies Record<CoverStyle, string>,
  writePrompt: "Write prompt",
  rewritePrompt: "Rewrite prompt",
  writing: "Writing…",
  prompt: "Prompt",
  promptPlaceholder: "Describe the image, or write it from the transcript.",
  model: "Model",
  models: { gemini: "Gemini (Nano Banana)", openai: "OpenAI gpt-image-1" } satisfies Record<CoverModel, string>,
  aspect: "Shape",
  aspects: { "3:4": "3:4 portrait", "4:3": "4:3 landscape", "1:1": "1:1 square" } satisfies Record<CoverAspect, string>,
  generate: "Generate image",
  generating: "Drawing… (up to a minute)",
  results: "Generated",
  resultsHint: "This session's images. Pick one, then use it.",
  noResults: "Nothing generated yet.",
  useAsCover: "Use as cover",
  useAsBanner: "Use as banner",
  used: (what: string) => `Set as the ${what}`,
  open: "Open",
}
