export const DASHBOARD = {
  title: "Dashboard",
  subtitle: "How GlotCast is doing: people, listening and content.",
  stats: {
    users: "Users",
    usersHint: (anonymous: string) => `${anonymous} guests`,
    newUsers: "New · 7 days",
    newUsersHint: "Accounts and guests created",
    listenersToday: "Listeners · today",
    listenersHint: (avg: string) => `${avg} a day on average`,
    published: "Published episodes",
    publishedHint: (drafts: string) => `${drafts} drafts or scheduled`,
  },
  dau: "Daily listeners",
  dauHint: "Distinct people who listened, per day (their local date), last 30 days.",
  listeners: "Listeners",
  top: "Top episodes",
  topHint: "Most distinct listeners over the last 30 days.",
  topEmpty: "Nobody has listened in the last 30 days.",
  listenersCount: (n: number) => `${n} ${n === 1 ? "listener" : "listeners"}`,
  content: "Content",
  contentHint: "What the app can show, and what is waiting.",
  openEpisodes: "All episodes",
  drafts: "Drafts",
  live: "Live",
}
