import { type EpisodeStatusFilter } from "@/domain/lists"

export const EPISODES = {
  title: "Episodes",
  subtitle: "Every episode, drafts included. Each one has up to three levels with their own audio and transcript.",
  new: "New episode",
  searchPlaceholder: "Search titles",
  allPodcasts: "All podcasts",
  podcastLabel: "Podcast",
  statuses: { all: "All", published: "Published", draft: "Drafts" } satisfies Record<EpisodeStatusFilter, string>,
  columns: {
    episode: "Episode",
    podcast: "Podcast",
    levels: "Levels",
    status: "Status",
    access: "Access",
    updated: "Updated",
  },
  pro: "Pro",
  free: "Free",
  emptyTitle: "No episodes",
  emptyFiltered: "No episode matches these filters.",
  emptyAll: "Create the first episode, then add its levels.",
  create: {
    title: "New episode",
    subtitle: "Start with the details; the levels, the transcripts and the cover come next.",
    submit: "Create episode",
    created: "Episode created — now add its levels",
    noPodcasts: "Create a podcast first: every episode belongs to one.",
  },
  form: {
    details: "Details",
    detailsHint: "What the episode is called and where it belongs.",
    podcast: "Podcast",
    pickPodcast: "Choose a podcast",
    title: "Title",
    number: "Number",
    numberHint: "Its place in the podcast.",
    description: "Description",
    isPro: "Pro episode",
    isProHint: "Only Pro listeners hear past the free preview.",
    images: "Artwork",
    imagesHint: "The cover (portrait) shows in lists, the banner (landscape) on the home slider.",
    cover: "Cover",
    banner: "Banner",
    saved: "Episode saved",
  },
  errors: {
    podcast: "Choose a podcast.",
    title: "Give the episode a title.",
    number: "A whole number from 0.",
    url: "Enter a full URL (https://…).",
  },
  editor: {
    back: "Episodes",
    tabs: { details: "Details", cover: "Cover art" },
    levelTab: (short: string) => short,
    unsavedDot: "Unsaved changes",
    hasLevel: "Has audio",
    notFound: "This episode doesn't exist (or was deleted).",
    publish: "Publish now",
    unpublish: "Unpublish",
    schedule: "Schedule…",
    reschedule: "Change date…",
    published: "Episode published",
    unpublished: "Episode is a draft again",
    scheduled: (when: string) => `Episode scheduled for ${when}`,
    scheduleTitle: "Schedule this episode",
    scheduleBody: "It goes live at this time (your time zone). Its podcast must be published too.",
    scheduleField: "Goes live at",
    scheduleSubmit: "Schedule",
    schedulePast: "Pick a time in the future (or publish now).",
    publishNoLevels: "This episode has no level yet: the app will show it without audio.",
    unpublishTitle: "Unpublish this episode?",
    unpublishBody: "It disappears from the app right away (listening progress is kept).",
    deleteTitle: "Delete this episode?",
    deleteBody: (title: string) =>
      `“${title}” and its levels will be removed for good, and taken out of lists and the home slider.`,
    deleted: "Episode deleted",
    menu: "More actions",
    delete: "Delete episode",
    podcastDraft: "Its podcast is a draft: nothing of it shows in the app until the podcast is published.",
    facts: { status: "Status", publishedAt: "Goes live", created: "Created", updated: "Updated", legacy: "Strapi id", id: "ID" },
    statusLine: { draft: "Draft — not in the app", scheduled: (when: string) => `Scheduled for ${when}`, published: (when: string) => `Live since ${when}` },
  },
}
