import { type IssueKind } from "@/domain/transcript"
import { type SaveProblem } from "@/domain/levelDraft"
import { type AudioCompression } from "@/services/AudioCompressionService"
import { type ChunkMode } from "@/domain/transcript"

export const LEVEL = {
  empty: (level: string) => `No ${level.toLowerCase()} level yet`,
  emptyHint: "Upload its audio (or paste a URL), transcribe it, check the lines, then save.",
  audio: {
    title: "Audio",
    hint: "An MP3 or any audio file. Compressing in the browser keeps uploads small.",
    upload: "Upload audio",
    replace: "Replace audio",
    compression: "Compression",
    presets: {
      none: "None — upload as is",
      low: "Light — 128 kbps",
      medium: "Medium — 64 kbps (recommended)",
      high: "Strong — 32 kbps",
    } satisfies Record<AudioCompression, string>,
    compressing: (pct: number) => `Compressing… ${pct}%`,
    uploading: (pct: number) => `Uploading… ${pct}%`,
    compressed: (from: string, to: string) => `Compressed ${from} → ${to}`,
    uploaded: "Audio uploaded",
    uploadFailed: "Upload failed",
    compressFailed: "Couldn't compress this file (upload it as is?)",
    notAudio: "That isn't an audio file.",
    urlLabel: "Audio URL",
    urlPlaceholder: "https://…/podcasts/episode.mp3",
    useUrl: "Use URL",
    transcribeAfter: "Transcribe after upload",
    duration: (d: string) => `Length ${d}`,
    noDuration: "Length unknown until the audio loads",
    loadFailed: "The browser couldn't load this audio (check the URL).",
  },
  transcribe: {
    title: "Transcription",
    hint: "AssemblyAI with speaker labels; word timings included.",
    start: "Transcribe",
    again: "Transcribe again",
    needAudio: "Add the audio first.",
    starting: "Sending the audio…",
    queued: "Queued at AssemblyAI…",
    processing: "Transcribing… (about a third of the audio's length)",
    completed: "Transcript ready",
    failed: "Transcription failed",
    elapsed: (s: string) => `${s} elapsed`,
    replaceTitle: "Replace the transcript?",
    replaceBody: "The lines on screen are replaced by the new transcription (Undo brings them back).",
    applied: (mode: string) => `Transcript replaced with ${mode.toLowerCase()} lines`,
    modes: { utterance: "Utterances", sentence: "Sentences", paragraph: "Paragraphs" } satisfies Record<ChunkMode, string>,
    modeHints: {
      utterance: "One line per speaker turn",
      sentence: "One line per sentence",
      paragraph: "One line per paragraph",
    } satisfies Record<ChunkMode, string>,
    chunkMode: "Lines",
    lines: (n: number) => `${n} ${n === 1 ? "line" : "lines"}`,
  },
  editor: {
    title: "Transcript",
    hint: "Click a line's time to play from there. Times are in seconds.",
    empty: "No lines yet: transcribe the audio, or save the level without a transcript.",
    follow: "Follow playback",
    speaker: "Speaker",
    noSpeaker: "—",
    newSpeaker: (s: string) => `New speaker ${s}`,
    start: "Start",
    end: "End",
    minus: (step: string) => `−${step} s`,
    plus: (step: string) => `+${step} s`,
    setStart: "Start at playhead",
    setEnd: "End at playhead",
    split: "Split at cursor",
    merge: "Merge with next",
    remove: "Delete line",
    play: "Play from here",
    undo: "Undo",
    redo: "Redo",
    words: "word timings",
    shortcuts: "Space play/pause · ←/→ 5 s · ⌘Z undo · ⌘⇧Z redo · ⌘↵ split at cursor (in a line)",
    issues: (n: number) => `${n} ${n === 1 ? "line needs" : "lines need"} attention`,
    jump: "Show",
  },
  issues: {
    empty: "Empty text",
    range: "Ends before it starts",
    overlap: "Overlaps the previous line",
    beyond: "Ends after the audio",
  } satisfies Record<IssueKind, string>,
  description: "Level description",
  descriptionHint: "Optional: a line about this level's version (shown in the app).",
  save: "Save level",
  saved: (level: string) => `${level} level saved`,
  discard: "Discard changes",
  discardTitle: "Discard this level's changes?",
  discardBody: "The audio, description and transcript go back to what is saved.",
  delete: "Delete level",
  deleteTitle: (level: string) => `Delete the ${level.toLowerCase()} level?`,
  deleteBody: "Its audio link and transcript are removed from the episode (the audio file stays in R2).",
  deleted: (level: string) => `${level} level deleted`,
  savedAt: (ago: string) => `Saved ${ago}`,
  notSaved: "Not saved yet",
  problems: {
    no_audio: "Add the audio first.",
    bad_url: "The audio URL isn't a valid http(s) URL.",
    no_duration: "Waiting for the audio's length (it loads in the player).",
    lines: "Fix the lines marked in red first.",
    busy: "Wait for the current action to finish.",
  } satisfies Record<SaveProblem, string>,
  player: {
    title: "Preview",
    rate: "Speed",
  },
}
