export const LISTS = {
  title: "Lists",
  subtitle: "Hand-picked, ordered episode collections for the home and discover screens.",
  new: "New list",
  columns: { list: "List", episodes: "Episodes", updated: "Updated" },
  emptyTitle: "No lists",
  emptyBody: "Create a list, then pick its episodes.",
  createTitle: "New list",
  name: "Name",
  slug: "Slug",
  slugHint: (preview: string) => (preview ? `Leave empty for “${preview}”.` : "Leave empty to make one from the name."),
  description: "Description",
  created: "List created",
  saved: "List saved",
  detailsTitle: "Details",
  detailsHint: "The app shows the name and description above the episodes.",
  episodes: "Episodes",
  episodesHint: "Drag to reorder. Drafts are kept but hidden in the app until published.",
  addEpisodes: "Add episodes",
  noEpisodes: "No episodes in this list yet.",
  saveOrder: "Save episodes",
  orderSaved: "Episodes saved",
  unsavedOrder: "The episode order has unsaved changes.",
  deleteTitle: "Delete this list?",
  deleteBody: (name: string) => `“${name}” is deleted for good and taken off the home and discover screens.`,
  deleted: "List deleted",
  notFound: "This list doesn't exist (or was deleted).",
  errors: { name: "Give the list a name.", slug: "Lowercase letters, digits and single dashes only." },
}
