export const PODCASTS = {
  title: "Podcasts",
  subtitle: "Shows, their categories and covers. New podcasts are drafts until published.",
  new: "New podcast",
  searchPlaceholder: "Search name or slug",
  columns: {
    podcast: "Podcast",
    categories: "Categories",
    episodes: "Episodes",
    status: "Status",
    updated: "Updated",
  },
  episodes: (published: number, total: number) => `${published} of ${total} live`,
  emptyTitle: "No podcasts",
  emptyFiltered: "No podcast matches this search.",
  emptyAll: "Create the first podcast to start adding episodes.",
  editor: {
    newTitle: "New podcast",
    newSubtitle: "A draft: its episodes reach the app once it is published.",
    editSubtitle: "Changes apply in the app as soon as you save.",
    details: "Details",
    detailsHint: "The name, the address and what the show is about.",
    name: "Name",
    slug: "Slug",
    slugHint: (preview: string) =>
      preview ? `Leave empty for “${preview}”.` : "Leave empty to make one from the name.",
    description: "Description",
    categories: "Categories",
    categoriesHint: "In display order. The first one is the main category.",
    addCategory: "Add a category",
    noCategories: "No categories yet",
    cover: "Cover",
    coverHint: "Square or portrait artwork. Upload, paste a URL or generate one.",
    published: "Published",
    publishedHint: "Visible in the app, with its published episodes.",
    draftHint: "A draft: hidden from the app, with all its episodes.",
    created: "Podcast created",
    saved: "Podcast saved",
    deleteTitle: "Delete this podcast?",
    deleteBody: (name: string) => `“${name}” will be removed for good.`,
    deleteBlocked: (n: number) =>
      `It still has ${n} ${n === 1 ? "episode" : "episodes"}: delete or move them first (the API refuses otherwise).`,
    deleted: "Podcast deleted",
    viewEpisodes: "Episodes",
    facts: "Facts",
    legacy: "Strapi id",
    createdAt: "Created",
    updatedAt: "Updated",
    publishedAt: "Published",
    episodeCount: "Episodes",
  },
  errors: {
    name: "Give the podcast a name.",
    slug: "Lowercase letters, digits and single dashes only.",
    url: "Enter a full URL (https://…).",
  },
}
