export const USERS = {
  title: "Users",
  subtitle: "Everyone with an account or a guest session.",
  searchPlaceholder: "Search email, name or user ID",
  columns: { user: "User", level: "Level", access: "Pro", created: "Signed up", seen: "Last seen" },
  guest: "Guest",
  pro: "Pro",
  emptyTitle: "No users found",
  emptyFiltered: "No one matches this search.",
  emptyAll: "No one has signed up yet.",
  detail: {
    back: "Users",
    notFound: "This user doesn't exist (or was deleted).",
    profile: "Profile",
    profileHint: "What the user told the app.",
    fields: {
      id: "User ID",
      email: "Email",
      name: "Name",
      type: "Type",
      level: "Level",
      native: "Native language",
      ui: "App language",
      translation: "Translates to",
      goal: "Daily goal",
      interests: "Interests",
      motivation: "Motivation",
      reminder: "Reminder",
      created: "Signed up",
      seen: "Last seen",
      seenHint: "updated at most once an hour",
      legacy: "Strapi user",
    },
    registered: "Registered",
    minutes: (n: number) => `${n} min`,
    motivations: { career: "Career", travel: "Travel", exams: "Exams", fun: "Fun", other: "Other" } as Record<string, string>,
    stats: {
      streak: "Streak",
      streakHint: (best: number) => `Best ${best} ${best === 1 ? "day" : "days"}`,
      days: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
      today: "Today",
      todayHint: (goal: string, met: boolean) => (met ? `Goal of ${goal} met` : `Goal ${goal}`),
      total: "Total listening",
      completed: (n: number) => `${n} ${n === 1 ? "episode" : "episodes"} completed`,
      words: "Saved words",
      wordsHint: (mastered: number, due: number) => `${mastered} mastered · ${due} due`,
    },
    week: "Last 7 days",
    weekHint: "Listening per day, the user's local dates.",
    minutesLabel: "Minutes",
    access: "Pro access",
    accessHint: "Backend-granted Pro: the app unlocks Pro episodes regardless of the store subscription.",
    accessOn: "Pro is granted",
    accessOff: "No backend Pro",
    granted: "Pro granted",
    revoked: "Pro removed",
    revokeTitle: "Remove Pro access?",
    revokeBody: (who: string) => `${who} loses backend Pro right away (a store subscription is not affected).`,
    revoke: "Remove Pro",
    auditNote: "Opening this page is recorded in the audit log.",
  },
}
